export const currencyNames = {
    usd: "United States Dollar",
    eur: "Euro",
    gbp: "British Pound Sterling",
    inr: "Indian Rupee",
    aud: "Australian Dollar",
    cad: "Canadian Dollar",
    sgd: "Singapore Dollar",
    chf: "Swiss Franc",
    myr: "Malaysian Ringgit",
    jpy: "Japanese Yen",
    cny: "Chinese Yuan",
    npr: "Nepalese Rupee",
    nzd: "New Zealand Dollar",
    thb: "Thai Baht",
    hkd: "Hong Kong Dollar",
    pkr: "Pakistani Rupee",
    bdt: "Bangladeshi Taka",
    idr: "Indonesian Rupiah",
    czk: "Czech Koruna",
    aed: "United Arab Emirates Dirham",
    afn: "Afghan Afghani",
    all: "Albanian Lek",
    amd: "Armenian Dram",
    ang: "Netherlands Antillean Guilder",
    aoa: "Angolan Kwanza",
    ars: "Argentine Peso",
    awg: "Aruban Florin",
    azn: "Azerbaijani Manat",
    bam: "Bosnia-Herzegovina Convertible Mark",
    bbd: "Barbadian Dollar",
    bgn: "Bulgarian Lev",
    bhd: "Bahraini Dinar",
    bif: "Burundian Franc",
    bmd: "Bermudan Dollar",
    bnd: "Brunei Dollar",
    bob: "Bolivian Boliviano",
    brl: "Brazilian Real",
    bsd: "Bahamian Dollar",
    btn: "Bhutanese Ngultrum",
    bwp: "Botswanan Pula",
    byn: "Belarusian Ruble",
    bzd: "Belize Dollar",
    clp: "Chilean Peso",
    cop: "Colombian Peso",
    crc: "Costa Rican Colón",
    cup: "Cuban Peso",
    dkk: "Danish Krone",
    dzd: "Algerian Dinar",
    egp: "Egyptian Pound",
    etb: "Ethiopian Birr",
    fjd: "Fijian Dollar",
    gel: "Georgian Lari",
    ghs: "Ghanaian Cedi",
    gip: "Gibraltar Pound",
    gtq: "Guatemalan Quetzal",
    hrk: "Croatian Kuna",
    htg: "Haitian Gourde",
    huf: "Hungarian Forint",
    ils: "Israeli New Shekel",
    iqd: "Iraqi Dinar",
    irr: "Iranian Rial",
    isk: "Icelandic Króna",
    jmd: "Jamaican Dollar",
    jod: "Jordanian Dinar",
    kes: "Kenyan Shilling",
    kgs: "Kyrgystani Som",
    khr: "Cambodian Riel",
    kmf: "Comorian Franc",
    krw: "South Korean Won",
    kwd: "Kuwaiti Dinar",
    kzt: "Kazakhstani Tenge",
    lbp: "Lebanese Pound",
    lkr: "Sri Lankan Rupee",
    ltl: "Lithuanian Litas",
    mad: "Moroccan Dirham",
    mdl: "Moldovan Leu",
    mnt: "Mongolian Tugrik",
    mop: "Macanese Pataca",
    mur: "Mauritian Rupee",
    mvr: "Maldivian Rufiyaa",
    mxn: "Mexican Peso",
    ngn: "Nigerian Naira",
    nok: "Norwegian Krone",
    omr: "Omani Rial",
    pen: "Peruvian Nuevo Sol",
    php: "Philippine Peso",
    pln: "Polish Złoty",
    pyg: "Paraguayan Guarani",
    qar: "Qatari Rial",
    ron: "Romanian Leu",
    rsd: "Serbian Dinar",
    rub: "Russian Ruble",
    sar: "Saudi Riyal",
    sek: "Swedish Krona",
    thb: "Thai Baht",
    try: "Turkish Lira",
    twd: "New Taiwan Dollar",
    tzs: "Tanzanian Shilling",
    uah: "Ukrainian Hryvnia",
    uyu: "Uruguayan Peso",
    vef: "Venezuelan Bolívar",
    vnd: "Vietnamese Dong",
    zar: "South African Rand"
}; 